### ISSUE TITLE
Change unordered marker from asterisk to dash

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/styleguide-markdown#3]
The currently used asterisk `*` should be changed to dashes `-`. The main reason is that asterisks `*` can be confused for bold/italic markers. There was also a [very long discussion][ref1] for [Prettier][] to also change the default to dashes to same reasons  [which was then adapted][ref2].
There are some other reasons like the alignment with the YAML spec which uses dashes for list items.

This guide will now also adapt to this improvement by changing the [default unordered list marker](https://arcticicestudio.github.io/styleguide-markdown/rules/lists.html) from asterisks `*` to dashes `-`.

[prettier]: https://prettier.io 
[ref1]: https://github.com/prettier/prettier/issues/4251#issue-310943939
[ref2]: https://github.com/prettier/prettier/pull/4440

**Comment by manishprivet** [comment]
This is causing a problem in `.md` files in my case, where I've to insert a Thematic break using `***` but Prettier is constantly changing it to `---`

Any possible solutions for it?

**Comment by arcticicestudio** [comment]
@manishprivet This change was only related to lists, but using `***` for [horizontal rules][md-hl] can be seen as problematic as the previously used `*` characters for lists. `---` on the other hand should be fine in any case because there are more than one dash without a whitespace. Anyway, if you still like to keep `***` you can simply [add a Prettier ignore comment above it][pi] to stop Prettier from formatting/changing it:

```md
<!-- prettier-ignore -->
***
```

[pi]: https://prettier.io/docs/en/ignore.html#markdown
[md-hl]: https://www.markdownguide.org/basic-syntax/#horizontal-rules
