### ISSUE TITLE
Bump remark-cli from 5.0.0 to 8.0.0

### ISSUE THREAD

**Issue by ghost** [arcticicestudio/styleguide-markdown#8]
https://github.com/arcticicestudio/styleguide-markdown/blob/880c5fbfec22ae2e4ad71699f497e2c8105189b5/package.json#L40

Hi, hate to go Dependabot on you 🤖 but this package's dependency tree contains a [low risk dependency issue](https://www.npmjs.com/advisories/786). Upgrading it to 8.0.0 on my side works perfectly fine, but gives a slightly annoying warning about this Remark preset's peer dependency

I am opening a PR to fix this for you 🙆‍♂️

**Comment by arcticicestudio** [comment]
Please see https://github.com/arcticicestudio/styleguide-markdown/pull/9#issuecomment-724256185
